### PR TITLE
Add namespace requirement, reject on basis of message instead of invalid settings

### PR DESCRIPTION
**Pull request by sperand-io**
@hankim813 @thehydroimpulse

### CODE REVIEW

**Comment by thehydroimpulse** [comment]
LGTM!

**Comment by hankim813** [comment]
@sperand-io lgtm, if you wanna add a release commit on top of this and deploy. @thehydroimpulse however, I believe all robo deploys are disabled so daniel can help you w the new deploy

**Comment by sperand-io** [comment]
@achille-roussel if you're looking at this integration I do think this cleans it up considerably while adding another layer of required validation

**Comment by achille-roussel** [comment]
Yep, I integrated the changes into #16

**Comment by sperand-io** [comment]
awesome.

**Pull request closed without merging**
